// <auto-generated />
using System;
using HotStuffApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotStuffApp.Migrations
{
    [DbContext(typeof(HotStuffAppDbContext))]
    [Migration("20260224092435_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotStuffApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Pizza",
                            Description = "Italian Style Pizzas"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Burgers",
                            Description = "Crispy & Juicy Burgers"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Indian",
                            Description = "Authentic Indian Cuisine"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Chinese",
                            Description = "Spicy Chinese Dishes"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Beverages",
                            Description = "Refreshing Drinks"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Desserts",
                            Description = "Sweet Treats"
                        });
                });

            modelBuilder.Entity("HotStuffApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HotStuffApp.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HotStuffApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Classic cheese pizza",
                            ImageUrl = "margherita.jpg",
                            ProductName = "Margherita Pizza",
                            ProductPrice = 299m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Loaded with veggies",
                            ImageUrl = "farmhouse.jpg",
                            ProductName = "Farmhouse Pizza",
                            ProductPrice = 399m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Paneer & capsicum",
                            ImageUrl = "paneer.jpg",
                            ProductName = "Peppy Paneer",
                            ProductPrice = 379m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Loaded chicken pizza",
                            ImageUrl = "chickenpizza.jpg",
                            ProductName = "Chicken Dominator",
                            ProductPrice = 449m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Classic veg burger",
                            ImageUrl = "vegburger.jpg",
                            ProductName = "Veg Burger",
                            ProductPrice = 149m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Extra cheese delight",
                            ImageUrl = "cheeseburger.jpg",
                            ProductName = "Cheese Burger",
                            ProductPrice = 179m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Description = "Crispy chicken patty",
                            ImageUrl = "chickenburger.jpg",
                            ProductName = "Chicken Burger",
                            ProductPrice = 199m,
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Double layer burger",
                            ImageUrl = "doubleburger.jpg",
                            ProductName = "Double Patty Burger",
                            ProductPrice = 249m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Description = "Creamy tomato gravy",
                            ImageUrl = "butterchicken.jpg",
                            ProductName = "Butter Chicken",
                            ProductPrice = 349m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Rich paneer curry",
                            ImageUrl = "paneerbutter.jpg",
                            ProductName = "Paneer Butter Masala",
                            ProductPrice = 299m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Spicy chicken biryani",
                            ImageUrl = "biryani.jpg",
                            ProductName = "Hyderabadi Biryani",
                            ProductPrice = 329m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "Yellow dal with tadka",
                            ImageUrl = "daltadka.jpg",
                            ProductName = "Dal Tadka",
                            ProductPrice = 199m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            Description = "Stir fried noodles",
                            ImageUrl = "noodles.jpg",
                            ProductName = "Veg Hakka Noodles",
                            ProductPrice = 199m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4,
                            Description = "Fried rice with chicken",
                            ImageUrl = "friedrice.jpg",
                            ProductName = "Chicken Fried Rice",
                            ProductPrice = 229m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4,
                            Description = "Manchurian gravy balls",
                            ImageUrl = "manchurian.jpg",
                            ProductName = "Veg Manchurian",
                            ProductPrice = 189m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Crispy rolls",
                            ImageUrl = "springroll.jpg",
                            ProductName = "Spring Rolls",
                            ProductPrice = 169m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5,
                            Description = "500ml chilled coke",
                            ImageUrl = "coke.jpg",
                            ProductName = "Coca Cola",
                            ProductPrice = 60m,
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5,
                            Description = "Chilled coffee",
                            ImageUrl = "coldcoffee.jpg",
                            ProductName = "Cold Coffee",
                            ProductPrice = 120m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 5,
                            Description = "Refreshing lime soda",
                            ImageUrl = "limesoda.jpg",
                            ProductName = "Fresh Lime Soda",
                            ProductPrice = 80m,
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 5,
                            Description = "Fresh mango milkshake",
                            ImageUrl = "mangoshake.jpg",
                            ProductName = "Mango Shake",
                            ProductPrice = 140m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 6,
                            Description = "Hot chocolate brownie",
                            ImageUrl = "brownie.jpg",
                            ProductName = "Chocolate Brownie",
                            ProductPrice = 149m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 6,
                            Description = "Vanilla chocolate sundae",
                            ImageUrl = "sundae.jpg",
                            ProductName = "Ice Cream Sundae",
                            ProductPrice = 129m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 6,
                            Description = "Traditional Indian sweet",
                            ImageUrl = "gulabjamun.jpg",
                            ProductName = "Gulab Jamun",
                            ProductPrice = 99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 6,
                            Description = "Creamy cheesecake slice",
                            ImageUrl = "cheesecake.jpg",
                            ProductName = "Cheesecake",
                            ProductPrice = 179m,
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("HotStuffApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotStuffApp.Models.Order", b =>
                {
                    b.HasOne("HotStuffApp.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotStuffApp.Models.OrderDetail", b =>
                {
                    b.HasOne("HotStuffApp.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotStuffApp.Models.Product", b =>
                {
                    b.HasOne("HotStuffApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotStuffApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HotStuffApp.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("HotStuffApp.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
